// ------------------------------------------------------------------------
// This file is generated by ts-css-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-css-loader
// ------------------------------------------------------------------------

// Default object containing all local CSS classes
declare const __styles: {
    "board-row": string;
    "boardRow": string;
    "status": string;
};
export default __styles;

// Named exports with local CSS classes whose names are valid identifiers
export const boardRow: string;
export const status: string;
