// ------------------------------------------------------------------------
// This file is generated by ts-css-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-css-loader
// ------------------------------------------------------------------------

// Object containing all local CSS classes
export const locals: {
    "game": string;
    "game-board": string;
    "gameBoard": string;
    "game-info": string;
    "gameInfo": string;
    "game-footerX": string;
    "gameFooterX": string;
};
