// ------------------------------------------------------------------------
// This file is generated by ts-css-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-css-loader
// ------------------------------------------------------------------------

// Object containing all local CSS classes
export const locals: {
    "board-row": string;
    "boardRow": string;
    "status": string;
};
