// ------------------------------------------------------------------------
// This file is generated by ts-css-loader and should not be edited by hand
// See: https://github.com/MortenHoustonLudvigsen/ts-css-loader
// ------------------------------------------------------------------------

// Default object containing all local CSS classes
declare const __styles: {
    "game": string;
    "game-board": string;
    "gameBoard": string;
    "game-info": string;
    "gameInfo": string;
    "game-footer": string;
    "gameFooter": string;
};
export default __styles;

// Named exports with local CSS classes whose names are valid identifiers
export const game: string;
export const gameBoard: string;
export const gameInfo: string;
export const gameFooter: string;
